from collections import namedtuple

element = namedtuple("element", ["name", "symbol", "atomic number","atomic mass", "melting_point", "boiling_point", "density", "description"]) 


elements = [
    element(name="Hydrogen", symbol="H", atomic_number=1, atomic_mass=1.008, melting_point=-259.16, boiling_point=-252.87, density=0.00008988, description="The lightest element, a highly reactive gas."),
    element(name="Helium", symbol="He", atomic_number=2, atomic_mass=4.0026, melting_point=-272.2, boiling_point=-268.93, density=0.0001786, description="A noble gas, very unreactive, used in balloons."),
    element(name="Lithium", symbol="Li", atomic_number=3, atomic_mass=6.94, melting_point=180.54, boiling_point=1342, density=0.534, description="A soft, silvery-white alkali metal, highly reactive."),
    element(name="Beryllium", symbol="Be", atomic_number=4, atomic_mass=9.0122, melting_point=1287, boiling_point=2471, density=1.85, description="A relatively rare alkaline earth metal, strong and light."),
    element(name="Boron", symbol="B", atomic_number=5, atomic_mass=10.81, melting_point=2076, boiling_point=3927, density=2.34, description="A metalloid, found in many minerals, used in borosilicate glass."),
    element(name="Carbon", symbol="C", atomic_number=6, atomic_mass=12.011, melting_point=3550, boiling_point=4027, density=2.267, description="Essential to all known life, exists in many allotropes like diamond and graphite."),
    element(name="Nitrogen", symbol="N", atomic_number=7, atomic_mass=14.007, melting_point=-210.01, boiling_point=-195.79, density=0.001251, description="A colorless, odorless gas, makes up most of the Earth's atmosphere."),
    element(name="Oxygen", symbol="O", atomic_number=8, atomic_mass=15.999, melting_point=-218.79, boiling_point=-182.96, density=0.001429, description="A highly reactive gas, essential for respiration and combustion."),
    element(name="Fluorine", symbol="F", atomic_number=9, atomic_mass=18.998, melting_point=-220, boiling_point=-188.1, density=0.001696, description="The most electronegative element, a highly reactive and corrosive gas."),
    element(name="Neon", symbol="Ne", atomic_number=10, atomic_mass=20.180, melting_point=-248.59, boiling_point=-246.08, density=0.0008999, description="A noble gas, used in lighting and signs."),
    element(name="Sodium", symbol="Na", atomic_number=11, atomic_mass=22.990, melting_point=97.79, boiling_point=882.9, density=0.968, description="A soft, silvery-white alkali metal, highly reactive."),
    element(name="Magnesium", symbol="Mg", atomic_number=12, atomic_mass=24.305, melting_point=650, boiling_point=1090, density=1.738, description="A light, strong alkaline earth metal, used in alloys."),
    element(name="Aluminum", symbol="Al", atomic_number=13, atomic_mass=26.982, melting_point=660.32, boiling_point=2519, density=2.70, description="A light, strong metal, widely used in construction and packaging."),
    element(name="Silicon", symbol="Si", atomic_number=14, atomic_mass=28.085, melting_point=1414, boiling_point=3265, density=2.33, description="A metalloid, abundant in the Earth's crust, used in semiconductors."),
    element(name="Phosphorus", symbol="P", atomic_number=15, atomic_mass=30.974, melting_point=44.15, boiling_point=280, density=1.823, description="An essential element for life, exists in several allotropes."),
    element(name="Sulfur", symbol="S", atomic_number=16, atomic_mass=32.06, melting_point=115.21, boiling_point=444.6, density=2.07, description="A yellow nonmetal, essential for proteins and other biological molecules."),
    element(name="Chlorine", symbol="Cl", atomic_number=17, atomic_mass=35.45, melting_point=-101.5, boiling_point=-34.04, density=0.003214, description="A greenish-yellow gas, highly reactive and toxic."),
    element(name="Argon", symbol="Ar", atomic_number=18, atomic_mass=39.948, melting_point=-189.35, boiling_point=-185.85, density=0.001784, description="A noble gas, used in lighting and welding."),
    element(name="Potassium", symbol="K", atomic_number=19, atomic_mass=39.098, melting_point=63.38, boiling_point=759, density=0.856, description="A soft, silvery-white alkali metal, highly reactive."),
    element(name="Calcium", symbol="Ca", atomic_number=20, atomic_mass=40.078, melting_point=842, boiling_point=1484, density=1.55, description="An alkaline earth metal, essential for bones and teeth."),
    element(name="Scandium", symbol="Sc", atomic_number=21, atomic_mass=44.956, melting_point=1541, boiling_point=2836, density=2.985, description="A silvery-white transition metal, used in some alloys."),
    element(name="Titanium", symbol="Ti", atomic_number=22, atomic_mass=47.867, melting_point=1668, boiling_point=3287, density=4.506, description="A strong, lightweight transition metal, used in aerospace and medical implants."),
    element(name="Vanadium", symbol="V", atomic_number=23, atomic_mass=50.942, melting_point=1910, boiling_point=3407, density=6.11, description="A hard, ductile transition metal, used in steel alloys."),
    element(name="Chromium", symbol="Cr", atomic_number=24, atomic_mass=51.996, melting_point=1907, boiling_point=2671, density=7.15, description="A hard, brittle transition metal, used in stainless steel and chrome plating."),
    element(name="Manganese", symbol="Mn", atomic_number=25, atomic_mass=54.938, melting_point=1246, boiling_point=2061, density=7.47, description="A brittle transition metal, essential in steel production."),
    element(name="Iron", symbol="Fe", atomic_number=26, atomic_mass=55.845, melting_point=1538, boiling_point=2862, density=7.874, description="A common and abundant transition metal, essential in steel and many other applications."),
    element(name="Cobalt", symbol="Co", atomic_number=27, atomic_mass=58.933, melting_point=1495, boiling_point=2927, density=8.90, description="A hard, ferromagnetic transition metal, used in alloys and batteries."),
    element(name="Nickel", symbol="Ni", atomic_number=28, atomic_mass=58.693, melting_point=1455, boiling_point=2913, density=8.902, description="A ductile and corrosion-resistant transition metal, used in alloys and plating."),
    element(name="Copper", symbol="Cu", atomic_number=29, atomic_mass=63.546, melting_point=1085, boiling_point=2562, density=8.96, description="A ductile and highly conductive transition metal, used in electrical wiring and plumbing."),
    element(name="Zinc", symbol="Zn", atomic_number=30, atomic_mass=65.38, melting_point=419.53, boiling_point=907, density=7.14, description="A bluish-white transition metal, used in galvanizing and alloys."),
    element(name="Gallium", symbol="Ga", atomic_number=31, atomic_mass=69.723, melting_point=29.76, boiling_point=2204, density=5.904, description="A soft, silvery metal, liquid at near room temperature, used in semiconductors."),
    element(name="Germanium", symbol="Ge", atomic_number=32, atomic_mass=72.63, melting_point=938.25, boiling_point=2833, density=5.323, description="A metalloid, used in semiconductors and fiber optics."),
    element(name="Arsenic", symbol="As", atomic_number=33, atomic_mass=74.922, melting_point=817, boiling_point=613, density=5.727, description="A metalloid, toxic, used in semiconductors and pesticides."),
    element(name="Selenium", symbol="Se", atomic_number=34, atomic_mass=78.971, melting_point=221, boiling_point=685, density=4.81, description="A nonmetal, essential in trace amounts, used in glass and photocells."),
    element(name="Bromine", symbol="Br", atomic_number=35, atomic_mass=79.904, melting_point=-7.2, boiling_point=58.8, density=3.12, description="A reddish-brown liquid nonmetal, corrosive and toxic."),
    element(name="Krypton", symbol="Kr", atomic_number=36, atomic_mass=83.798, melting_point=-157.2, boiling_point=-153.4, density=0.003733, description="A noble gas, used in lighting and lasers."),
    element(name="Rubidium", symbol="Rb", atomic_number=37, atomic_mass=85.468, melting_point=39.3, boiling_point=688, density=1.532, description="A soft, silvery-white alkali metal, highly reactive."),
    element(name="Strontium", symbol="Sr", atomic_number=38, atomic_mass=87.62, melting_point=777, boiling_point=1382, density=2.64, description="An alkaline earth metal, used in fireworks and pyrotechnics."),
    element(name="Yttrium", symbol="Y", atomic_number=39, atomic_mass=88.906, melting_point=1526, boiling_point=3345, density=4.472, description="A silvery-metallic transition metal, used in phosphors and lasers."),
    element(name="Zirconium", symbol="Zr", atomic_number=40, atomic_mass=91.224, melting_point=1855, boiling_point=4409, density=6.52, description="A strong, corrosion-resistant transition metal, used in nuclear reactors and ceramics."),
    element(name="Niobium", symbol="Nb", atomic_number=41, atomic_mass=92.906, melting_point=2468, boiling_point=4744, density=8.57, description="A ductile, corrosion-resistant transition metal, used in alloys and superconductors."),
    element(name="Molybdenum", symbol="Mo", atomic_number=42, atomic_mass=95.95, melting_point=2623, boiling_point=4639, density=10.28, description="A hard, silvery-white transition metal, used in high-strength alloys."),
    element(name="Technetium", symbol="Tc", atomic_number=43, atomic_mass=98, melting_point=2157, boiling_point=4265, density=11.5, description="A radioactive transition metal, used in medical imaging."),
    element(name="Ruthenium", symbol="Ru", atomic_number=44, atomic_mass=101.07, melting_point=2334, boiling_point=4150, density=12.45, description="A rare transition metal, used in electrical contacts and catalysts."),
    element(name="Rhodium", symbol="Rh", atomic_number=45, atomic_mass=102.906, melting_point=1964, boiling_point=3695, density=12.41, description="A rare, silvery-white transition metal, used in catalysts and jewelry."),
    element(name="Palladium", symbol="Pd", atomic_number=46, atomic_mass=106.42, melting_point=1554.9, boiling_point=2963, density=12.023, description="A rare, silvery-white transition metal, used in catalytic converters and electronics."),
    element(name="Silver", symbol="Ag", atomic_number=47, atomic_mass=107.868, melting_point=961.78, boiling_point=2162, density=10.49, description="A precious metal, highly conductive, used in jewelry, electronics, and photography."),
    element(name="Cadmium", symbol="Cd", atomic_number=48, atomic_mass=112.414, melting_point=321.07, boiling_point=767, density=8.65, description="A soft, bluish-white transition metal, toxic, used in batteries and coatings."),
    element(name="Indium", symbol="In", atomic_number=49, atomic_mass=114.818, melting_point=156.6, boiling_point=2072, density=7.31, description="A soft, silvery-white metal, used in solders and touch screens."),
    element(name="Tin", symbol="Sn", atomic_number=50, atomic_mass=118.710, melting_point=231.93, boiling_point=2602, density=7.31, description="A soft, malleable metal, used in alloys and coatings."),
    element(name="Promethium", symbol="Pm", atomic_number=61, atomic_mass=145, melting_point=1080, boiling_point=3027, density=7.26, description="A radioactive rare earth metal."),
    element(name="Samarium", symbol="Sm", atomic_number=62, atomic_mass=150.36, melting_point=1072, boiling_point=1900, density=7.52, description="A silvery rare earth metal, used in magnets and nuclear reactors."),
    element(name="Europium", symbol="Eu", atomic_number=63, atomic_mass=151.964, melting_point=826, boiling_point=1529, density=5.244, description="A soft, silvery-white rare earth metal, highly reactive."),
    element(name="Gadolinium", symbol="Gd", atomic_number=64, atomic_mass=157.25, melting_point=1313, boiling_point=3000, density=7.90, description="A silvery-white rare earth metal, used in magnets and nuclear control rods."),
    element(name="Terbium", symbol="Tb", atomic_number=65, atomic_mass=158.925, melting_point=1356, boiling_point=3230, density=8.23, description="A silvery-white rare earth metal, used in lasers and magneto-optical devices."),
    element(name="Dysprosium", symbol="Dy", atomic_number=66, atomic_mass=162.500, melting_point=1412, boiling_point=2562, density=8.55, description="A silvery-white rare earth metal, used in magnets and nuclear control rods."),
    element(name="Holmium", symbol="Ho", atomic_number=67, atomic_mass=164.930, melting_point=1474, boiling_point=2720, density=8.80, description="A silvery-white rare earth metal, used in lasers and nuclear control rods."),
    element(name="Erbium", symbol="Er", atomic_number=68, atomic_mass=167.259, melting_point=1529, boiling_point=2868, density=9.066, description="A silvery-white rare earth metal, used in lasers and optical fibers."),
    element(name="Thulium", symbol="Tm", atomic_number=69, atomic_mass=168.934, melting_point=1545, boiling_point=1950, density=9.321, description="A silvery-gray rare earth metal, used in portable X-ray machines."),
    element(name="Ytterbium", symbol="Yb", atomic_number=70, atomic_mass=173.045, melting_point=824, boiling_point=1196, density=6.90, description="A soft, malleable rare earth metal, used in stress gauges."),
    element(name="Lutetium", symbol="Lu", atomic_number=71, atomic_mass=174.967, melting_point=1663, boiling_point=3315, density=9.841, description="A silvery-white rare earth metal, used in catalysts and nuclear medicine."),
    element(name="Hafnium", symbol="Hf", atomic_number=72, atomic_mass=178.49, melting_point=2233, boiling_point=4603, density=13.31, description="A silvery-gray transition metal, used in nuclear control rods and high-temperature alloys."),
    element(name="Tantalum", symbol="Ta", atomic_number=73, atomic_mass=180.948, melting_point=3017, boiling_point=5458, density=16.65, description="A rare, hard, blue-gray transition metal, highly corrosion-resistant."),
    element(name="Tungsten", symbol="W", atomic_number=74, atomic_mass=183.84, melting_point=3422, boiling_point=5555, density=19.30, description="A hard, rare transition metal, with the highest melting point of all metals."),
    element(name="Rhenium", symbol="Re", atomic_number=75, atomic_mass=186.207, melting_point=3186, boiling_point=5596, density=21.02, description="A rare, heavy, silvery-white transition metal, used in high-temperature alloys."),
    element(name="Osmium", symbol="Os", atomic_number=76, atomic_mass=190.23, melting_point=3033, boiling_point=5012, density=22.61, description="A hard, brittle, bluish-white transition metal, the densest naturally occurring element."),
    element(name="Iridium", symbol="Ir", atomic_number=77, atomic_mass=192.217, melting_point=2446, boiling_point=4428, density=22.65, description="A hard, brittle, silvery-white transition metal, highly corrosion-resistant."),
    element(name="Platinum", symbol="Pt", atomic_number=78, atomic_mass=195.084, melting_point=1768.3, boiling_point=3825, density=21.45, description="A precious, silvery-white transition metal, used in jewelry and catalytic converters."),
    element(name="Gold", symbol="Au", atomic_number=79, atomic_mass=196.967, melting_point=1064.18, boiling_point=2856, density=19.30, description="A precious, soft, yellow transition metal, highly conductive and corrosion-resistant."),
    element(name="Mercury", symbol="Hg", atomic_number=80, atomic_mass=200.592, melting_point=-38.83, boiling_point=356.73, density=13.534, description="A heavy, silvery liquid transition metal, toxic."),
    element(name="Thallium", symbol="Tl", atomic_number=81, atomic_mass=204.383, melting_point=304, boiling_point=1473, density=11.85, description="A soft, malleable, bluish-white metal, highly toxic."),
    element(name="Lead", symbol="Pb", atomic_number=82, atomic_mass=207.2, melting_point=327.5, boiling_point=1749, density=11.34, description="A soft, malleable, heavy metal, toxic."),
    element(name="Bismuth", symbol="Bi", atomic_number=83, atomic_mass=208.980, melting_point=271.5, boiling_point=1564, density=9.78, description="A brittle, silvery-white metal, used in alloys and pharmaceuticals."),
    element(name="Polonium", symbol="Po", atomic_number=84, atomic_mass=209, melting_point=254, boiling_point=962, density=9.196, description="A rare and highly radioactive metal."),
    element(name="Astatine", symbol="At", atomic_number=85, atomic_mass=210, melting_point=302, boiling_point=337, density=7, description="A rare and highly radioactive metalloid."),
    element(name="Radon", symbol="Rn", atomic_number=86, atomic_mass=222, melting_point=-71, boiling_point=-61.7, density=0.00973, description="A radioactive noble gas."),
    element(name="Francium", symbol="Fr", atomic_number=87, atomic_mass=223, melting_point=27, boiling_point=677, density=2.48, description="A highly radioactive alkali metal."),
    element(name="Radium", symbol="Ra", atomic_number=88, atomic_mass=226, melting_point=700, boiling_point=1737, density=5.5, description="A highly radioactive alkaline earth metal."),
    element(name="Actinium", symbol="Ac", atomic_number=89, atomic_mass=227, melting_point=1050, boiling_point=3200, density=10, description="A radioactive metal."),
    element(name="Thorium", symbol="Th", atomic_number=90, atomic_mass=232.038, melting_point=1750, boiling_point=4788, density=11.72, description="A radioactive metal, used in nuclear fuel."),
    element(name="Protactinium", symbol="Pa", atomic_number=91, atomic_mass=231.036, melting_point=1568, boiling_point=4000, density=15.37, description="A radioactive metal."),
    element(name="Uranium", symbol="U", atomic_number=92, atomic_mass=238.029, melting_point=1135, boiling_point=4131, density=19.05, description="A radioactive metal, used in nuclear fuel and weapons."),
    element(name="Neptunium", symbol="Np", atomic_number=93, atomic_mass=237, melting_point=637, boiling_point=4175, density=20.45, description="A radioactive metal."),
    element(name="Plutonium", symbol="Pu", atomic_number=94, atomic_mass=244, melting_point=640, boiling_point=3228, density=19.84, description="A radioactive metal, used in nuclear weapons and reactors."),
    element(name="Americium", symbol="Am", atomic_number=95, atomic_mass=243, melting_point=1176, boiling_point=2607, density=13.67, description="A radioactive metal, used in smoke detectors."),
    element(name="Curium", symbol="Cm", atomic_number=96, atomic_mass=247, melting_point=1344, boiling_point=3110, density=13.51, description="A radioactive metal."),
    element(name="Berkelium", symbol="Bk", atomic_number=97, atomic_mass=247, melting_point=986, boiling_point=2900, density=14.78, description="A radioactive metal."),
    element(name="Californium", symbol="Cf", atomic_number=98, atomic_mass=251, melting_point=900, boiling_point=1470, density=15.1, description="A radioactive metal, used in neutron sources."),
    element(name="Einsteinium", symbol="Es", atomic_number=99, atomic_mass=252, melting_point=860, boiling_point=996, density=8.84, description="A radioactive metal."),
    element(name="Fermium", symbol="Fm", atomic_number=100, atomic_mass=257, melting_point=1527, boiling_point="None", density="None", description="A radioactive metal."),
    element(name="Mendelevium", symbol="Md", atomic_number=101, atomic_mass=258, melting_point=827, boiling_point="None", density="None", description="A radioactive metal."),
    element(name="Nobelium", symbol="No", atomic_number=102, atomic_mass=259, melting_point=827, boiling_point="None", density="None", description="A radioactive metal."),
    element(name="Lawrencium", symbol="Lr", atomic_number=103, atomic_mass=262, melting_point=1627, boiling_point="None", density="None", description="A radioactive metal."),
    element(name="Rutherfordium", symbol="Rf", atomic_number=104, atomic_mass=267, melting_point=2100, boiling_point=5800, density=23.2, description="A radioactive synthetic element."),
    element(name="Dubnium", symbol="Db", atomic_number=105, atomic_mass=270, melting_point="None", boiling_point="None", density=29.3, description="A radioactive synthetic element."),
    element(name="Seaborgium", symbol="Sg", atomic_number=106, atomic_mass=271, melting_point="None", boiling_point="None", density=35.0, description="A radioactive synthetic element."),
    element(name="Bohrium", symbol="Bh", atomic_number=107, atomic_mass=272, melting_point="None", boiling_point="None", density=37.1, description="A radioactive synthetic element."),
    element(name="Hassium", symbol="Hs", atomic_number=108, atomic_mass=277, melting_point="None", boiling_point="None", density=40.7, description="A radioactive synthetic element."),
    element(name="Meitnerium", symbol="Mt", atomic_number=109, atomic_mass=276, melting_point="None", boiling_point="None", density=37.4, description="A radioactive synthetic element."),
    element(name="Darmstadtium", symbol="Ds", atomic_number=110, atomic_mass=281, melting_point="None", boiling_point="None", density=34.8, description="A radioactive synthetic element."),
    element(name="Roentgenium", symbol="Rg", atomic_number=111, atomic_mass=280, melting_point="None", boiling_point="None", density=28.7, description="A radioactive synthetic element."),
    element(name="Copernicium", symbol="Cn", atomic_number=112, atomic_mass=285, melting_point="None", boiling_point="None", density=23.7, description="A radioactive synthetic element."),
    element(name="Nihonium", symbol="Nh", atomic_number=113, atomic_mass=286, melting_point="None", boiling_point="None", density=16, description="A radioactive synthetic element."),
    element(name="Flerovium", symbol="Fl", atomic_number=114, atomic_mass=289, melting_point="None", boiling_point="None", density=14, description="A radioactive synthetic element."),
    element(name="Moscovium", symbol="Mc", atomic_number=115, atomic_mass=290, melting_point="None", boiling_point="None", density=13.5, description="A radioactive synthetic element."),
    element(name="Livermorium", symbol="Lv", atomic_number=116, atomic_mass=293, melting_point="None", boiling_point="None", density=12.9, description="A radioactive synthetic element."),
    element(name="Tennessine", symbol="Ts", atomic_number=117, atomic_mass=294, melting_point="None", boiling_point="None", density=7.2, description="A radioactive synthetic element."),
    element(name="Oganesson", symbol="Og", atomic_number=118, atomic_mass=294, melting_point="None", boiling_point="None", density=4.95, description="A radioactive synthetic element."),
    element(name="Element 119", symbol="Uue", atomic_number=119, atomic_mass="None", melting_point="None", boiling_point="None", density="None", description="Hypothetical element."),
]

